### ISSUE TITLE
Profile screen

### ISSUE THREAD

**Issue by samgamage** [medmanager/frontend#45]
This screen should be very basic. We just want to be able to display the information captured in the registration process. We could add on additional fields like gender, birthday, profile picture to the user if we feel the profile screen should be able to display this information.

One could make the argument that the profile screen is pointless and that we should scrap it and in favor of just using the settings screen in the tab bar. This is up for discussion.

Dribbble inspiration:
- https://dribbble.com/shots/15131492-uStock-Profile-Community
- https://dribbble.com/shots/6280231-MediKeen-A-Health-app

**Comment by Loweida98** [comment]
I think a combination of settings and profile would be the best option. My thoughts are we could display their name at the top and have their email (with an option to click on it and change it if we want to add a side feature) and a tab to do the same with the password (not displaying the password though of course). Below that would be a tab for notifications which would bring you to a notification settings screen to make all the appropriate changes. Lastly there would be any additional settings and finally a sign out option at the bottom. May be a bit cluttered, but i'll have a better picture when I actually get to designing!
